### PR TITLE
Quote's font updated

### PR DESCRIPTION
**Pull request by Volley-Freak**
Font of quote as well as author is updated. Hope you would like it.

analog

Close : [#36](https://github.com/Sanket1308/analog-clock/issues/36)

### CODE REVIEW

**Comment by Sanket1308** [comment]
Make it look professional and simple.

**Comment by Volley-Freak** [comment]
> Make it look professional and simple.

Okay will make the changes

**Comment by Volley-Freak** [comment]
> Make it look professional and simple.
Screenshot at Oct 09 19-21-00
is that okay?

**Comment by Sanket1308** [comment]
Yes, go ahead!

**Comment by Volley-Freak** [comment]
> Yes, go ahead!

it was on my local. I hadn't pushed that.
Actually was showing you.

**Comment by Volley-Freak** [comment]
> > Yes, go ahead!
> 
> it was on my local. I hadn't pushed that. Actually was showing you.

@Sanket1308 i've create PR merge that for latest changes.

**Comment by Volley-Freak** [comment]
And please add label of hacktoberfest-accepted to this PR @Sanket1308

**Pull request merged**
