### PR TITLE
Removed change theme text and added sun/moon icon

### PR DESCRIPTION
**Pull request by Shivendra-Pandey**
@Sanket1308 please review it .

### CODE REVIEW

**Review by Sanket1308 — CHANGES_REQUESTED** [review]
Great work!🚀 You need to change a little before making a PR.
- Move the toggle button from centre to upper right side of the screen.

**Comment by Shivendra-Pandey** [comment]
> Great work!🚀 You need to change a little before making a PR.
> 
> * Move the toggle button from centre to upper right side of the screen.

@Sanket1308 please review the changes .

**Comment by Sanket1308** [comment]
Great job, @Shivendra-Pandey . Really nice implementation. 🚀
But, this branch has conflicts that must be resolved. It will be great if you fix that at make another PR. ✔

**Comment by Shivendra-Pandey** [comment]
> Great job, @Shivendra-Pandey . Really nice implementation. 🚀 But, this branch has conflicts that must be resolved. It will be great if you fix that at make another PR. ✔

@Sanket1308 merge conflicts resolved

**Pull request merged**
