### PR TITLE
Added Random quote

### PR DESCRIPTION
**Pull request by yasaswini999**
and  also fixed the alignment of the DarkTheme button
image
image
Do let me know if you had any improvements to make @Sanket1308

### CODE REVIEW

**Comment by Sanket1308** [comment]
Great job, @yasaswini999 . Really nice implementation. 🚀
But, this branch has conflicts that must be resolved. It will be great if you fix that at make another PR. ✔

**Comment by yasaswini999** [comment]
@Sanket1308 yeah sure ! Give me some time

**Comment by yasaswini999** [comment]
@Sanket1308 you can merge PR now

**Comment by Sanket1308** [comment]
Good work!

**Pull request merged**
