### PR TITLE
update footer with logos

### PR DESCRIPTION
**Pull request by zainbinfurqan**
update footer with logos

### CODE REVIEW

**Comment by zainbinfurqan** [comment]
@Sanket1308  Can you please review

**Comment by Sanket1308** [comment]
Add a upward arrow at the bottom
- On clicking it, it will show the github, linkedin and producthunt logo.
- On second click, they will go back inside

**Comment by Sanket1308** [comment]
> Add a upward arrow at the bottom
> 
> * On clicking it, it will show the github, linkedin and producthunt logo.
> * On second click, they will go back inside

Check this.

**Comment by zainbinfurqan** [comment]
> > Add a upward arrow at the bottom
> > 
> > * On clicking it, it will show the github, linkedin and producthunt logo.
> > * On second click, they will go back inside
> 
> Check this.

got the first point, can you explain 2nd one please.

**Comment by Sanket1308** [comment]
On clicking the button again all the other options which came out from it will go back inside like drawer menu

**Pull request closed without merging**
